-- Replace UUID user identifiers with database-generated numeric identifiers.
-- app_state keeps workspace UUIDs and user IDs in one owner_id column, so that
-- column remains text while user-owned rows store the numeric ID as text.

CREATE TEMP TABLE app_user_id_map ON COMMIT DROP AS
SELECT
  id AS old_id,
  row_number() OVER (ORDER BY created_at, id)::bigint AS new_id
FROM app_users;

ALTER TABLE app_users
  ADD COLUMN numeric_id bigint GENERATED BY DEFAULT AS IDENTITY;

UPDATE app_users AS users
SET numeric_id = mapping.new_id
FROM app_user_id_map AS mapping
WHERE users.id = mapping.old_id;

ALTER TABLE app_users
  ADD CONSTRAINT app_users_numeric_id_key UNIQUE (numeric_id);

ALTER TABLE workspaces
  DROP CONSTRAINT IF EXISTS workspaces_created_by_fkey,
  ADD COLUMN created_by_numeric bigint;
UPDATE workspaces AS workspaces
SET created_by_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE workspaces.created_by = mapping.old_id;
ALTER TABLE workspaces DROP COLUMN created_by;
ALTER TABLE workspaces RENAME COLUMN created_by_numeric TO created_by;
ALTER TABLE workspaces
  ADD CONSTRAINT workspaces_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE workspace_members
  DROP CONSTRAINT IF EXISTS workspace_members_user_id_fkey,
  DROP CONSTRAINT IF EXISTS workspace_members_pkey,
  ADD COLUMN user_id_numeric bigint;
UPDATE workspace_members AS members
SET user_id_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE members.user_id = mapping.old_id;
ALTER TABLE workspace_members DROP COLUMN user_id;
ALTER TABLE workspace_members RENAME COLUMN user_id_numeric TO user_id;
ALTER TABLE workspace_members ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE workspace_members
  ADD CONSTRAINT workspace_members_pkey PRIMARY KEY (workspace_id, user_id),
  ADD CONSTRAINT workspace_members_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES app_users(numeric_id) ON DELETE CASCADE;

ALTER TABLE app_state
  DROP CONSTRAINT IF EXISTS app_state_pkey,
  DROP CONSTRAINT IF EXISTS app_state_updated_by_fkey,
  ADD COLUMN owner_id_text text,
  ADD COLUMN updated_by_numeric bigint;
UPDATE app_state AS state
SET owner_id_text = COALESCE(
  (SELECT mapping.new_id::text FROM app_user_id_map AS mapping WHERE state.owner_id::text = mapping.old_id::text),
  CASE
    WHEN state.owner_id::text = '00000000-0000-4000-8000-000000000000' THEN 'platform'
    ELSE state.owner_id::text
  END
),
updated_by_numeric = (
  SELECT mapping.new_id
  FROM app_user_id_map AS mapping
  WHERE state.updated_by = mapping.old_id
);
ALTER TABLE app_state DROP COLUMN owner_id;
ALTER TABLE app_state DROP COLUMN updated_by;
ALTER TABLE app_state RENAME COLUMN owner_id_text TO owner_id;
ALTER TABLE app_state RENAME COLUMN updated_by_numeric TO updated_by;
ALTER TABLE app_state
  ADD CONSTRAINT app_state_pkey PRIMARY KEY (scope, owner_id, key),
  ADD CONSTRAINT app_state_updated_by_fkey
  FOREIGN KEY (updated_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE audit_logs
  DROP CONSTRAINT IF EXISTS audit_logs_actor_user_id_fkey,
  ADD COLUMN actor_user_id_numeric bigint;
UPDATE audit_logs AS logs
SET actor_user_id_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE logs.actor_user_id = mapping.old_id;
ALTER TABLE audit_logs DROP COLUMN actor_user_id;
ALTER TABLE audit_logs RENAME COLUMN actor_user_id_numeric TO actor_user_id;
ALTER TABLE audit_logs
  ADD CONSTRAINT audit_logs_actor_user_id_fkey
  FOREIGN KEY (actor_user_id) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE companies
  DROP CONSTRAINT IF EXISTS companies_created_by_fkey,
  DROP CONSTRAINT IF EXISTS companies_updated_by_fkey,
  ADD COLUMN created_by_numeric bigint,
  ADD COLUMN updated_by_numeric bigint;
UPDATE companies AS companies
SET created_by_numeric = created_mapping.new_id
FROM app_user_id_map AS created_mapping
WHERE companies.created_by = created_mapping.old_id;
UPDATE companies AS companies
SET updated_by_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE companies.updated_by = mapping.old_id;
ALTER TABLE companies DROP COLUMN created_by;
ALTER TABLE companies DROP COLUMN updated_by;
ALTER TABLE companies RENAME COLUMN created_by_numeric TO created_by;
ALTER TABLE companies RENAME COLUMN updated_by_numeric TO updated_by;
ALTER TABLE companies
  ADD CONSTRAINT companies_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL,
  ADD CONSTRAINT companies_updated_by_fkey
  FOREIGN KEY (updated_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE funding_programs
  DROP CONSTRAINT IF EXISTS funding_programs_created_by_fkey,
  DROP CONSTRAINT IF EXISTS funding_programs_updated_by_fkey,
  ADD COLUMN created_by_numeric bigint,
  ADD COLUMN updated_by_numeric bigint;
UPDATE funding_programs AS programs
SET created_by_numeric = created_mapping.new_id
FROM app_user_id_map AS created_mapping
WHERE programs.created_by = created_mapping.old_id;
UPDATE funding_programs AS programs
SET updated_by_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE programs.updated_by = mapping.old_id;
ALTER TABLE funding_programs DROP COLUMN created_by;
ALTER TABLE funding_programs DROP COLUMN updated_by;
ALTER TABLE funding_programs RENAME COLUMN created_by_numeric TO created_by;
ALTER TABLE funding_programs RENAME COLUMN updated_by_numeric TO updated_by;
ALTER TABLE funding_programs
  ADD CONSTRAINT funding_programs_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL,
  ADD CONSTRAINT funding_programs_updated_by_fkey
  FOREIGN KEY (updated_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE funding_packages
  DROP CONSTRAINT IF EXISTS funding_packages_created_by_fkey,
  ADD COLUMN created_by_numeric bigint;
UPDATE funding_packages AS packages
SET created_by_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE packages.created_by = mapping.old_id;
ALTER TABLE funding_packages DROP COLUMN created_by;
ALTER TABLE funding_packages RENAME COLUMN created_by_numeric TO created_by;
ALTER TABLE funding_packages
  ADD CONSTRAINT funding_packages_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE funding_package_runs
  DROP CONSTRAINT IF EXISTS funding_package_runs_requested_by_user_id_fkey,
  ADD COLUMN requested_by_user_id_numeric bigint;
UPDATE funding_package_runs AS runs
SET requested_by_user_id_numeric = mapping.new_id
FROM app_user_id_map AS mapping
WHERE runs.requested_by_user_id = mapping.old_id;
ALTER TABLE funding_package_runs DROP COLUMN requested_by_user_id;
ALTER TABLE funding_package_runs RENAME COLUMN requested_by_user_id_numeric TO requested_by_user_id;
ALTER TABLE funding_package_runs
  ADD CONSTRAINT funding_package_runs_requested_by_user_id_fkey
  FOREIGN KEY (requested_by_user_id) REFERENCES app_users(numeric_id) ON DELETE SET NULL;

ALTER TABLE app_users DROP CONSTRAINT app_users_pkey;
ALTER TABLE app_users RENAME COLUMN id TO legacy_id;
ALTER TABLE app_users RENAME COLUMN numeric_id TO id;
ALTER TABLE app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE app_users DROP COLUMN legacy_id;
ALTER TABLE app_users ALTER COLUMN id SET GENERATED ALWAYS;

SELECT setval(
  pg_get_serial_sequence('app_users', 'id'),
  COALESCE((SELECT MAX(id) FROM app_users), 1),
  true
);
