-- Replace UUID company identifiers with database-generated numeric identifiers.

CREATE TEMP TABLE company_id_map ON COMMIT DROP AS
SELECT
  id AS old_id,
  row_number() OVER (ORDER BY created_at, id)::bigint AS new_id
FROM companies;

ALTER TABLE companies
  ADD COLUMN numeric_id bigint GENERATED BY DEFAULT AS IDENTITY;

UPDATE companies AS companies
SET numeric_id = mapping.new_id
FROM company_id_map AS mapping
WHERE companies.id::text = mapping.old_id::text;

ALTER TABLE companies
  ADD CONSTRAINT companies_numeric_id_key UNIQUE (numeric_id);

ALTER TABLE funding_packages
  DROP CONSTRAINT IF EXISTS funding_packages_company_id_fkey,
  ADD COLUMN company_id_numeric bigint;
UPDATE funding_packages AS packages
SET company_id_numeric = mapping.new_id
FROM company_id_map AS mapping
WHERE packages.company_id::text = mapping.old_id::text;
ALTER TABLE funding_packages DROP COLUMN company_id;
ALTER TABLE funding_packages RENAME COLUMN company_id_numeric TO company_id;
ALTER TABLE funding_packages ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE funding_packages
  ADD CONSTRAINT funding_packages_company_id_fkey
  FOREIGN KEY (company_id) REFERENCES companies(numeric_id) ON DELETE CASCADE;

ALTER TABLE companies DROP CONSTRAINT companies_pkey;
ALTER TABLE companies RENAME COLUMN id TO legacy_id;
ALTER TABLE companies RENAME COLUMN numeric_id TO id;
ALTER TABLE companies ADD CONSTRAINT companies_pkey PRIMARY KEY (id);
ALTER TABLE companies DROP COLUMN legacy_id;
ALTER TABLE companies ALTER COLUMN id SET GENERATED ALWAYS;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'companies_workspace_name_key'
  ) THEN
    ALTER TABLE companies
      ADD CONSTRAINT companies_workspace_name_key UNIQUE (workspace_id, name);
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('companies', 'id'),
  COALESCE((SELECT MAX(id) FROM companies), 1),
  true
);
