import http from 'node:http'
import { randomBytes } from 'node:crypto'
import { lookup } from 'node:dns/promises'
import { existsSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { URL } from 'node:url'

const setupRoot = process.env.SETUP_ROOT || '/setup'
const token = process.env.SETUP_TOKEN || ''
const serverAddress = process.env.SERVER_ADDRESS || 'the VPS address'
const envFile = join(setupRoot, '.env.production')
const exampleEnvFile = join(setupRoot, '.env.production.example')
const overrideFile = join(setupRoot, 'docker-compose.proxy.yml')
const completionFile = join(setupRoot, '.setup-complete')
const statusFile = join(setupRoot, '.setup-status.json')
const port = Number(process.env.SETUP_PORT || 8090)
const bindAddress = process.env.SETUP_BIND_ADDRESS || '0.0.0.0'
const ttlSeconds = Number(process.env.SETUP_TTL_SECONDS || 86400)

if (!token) throw new Error('SETUP_TOKEN is required.')
if (!Number.isInteger(ttlSeconds) || ttlSeconds < 60) throw new Error('SETUP_TTL_SECONDS must be at least 60 seconds.')

let setupCompleted = existsSync(completionFile)
let setupInput = null

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function isValidDomain(value) {
  const domain = value.trim().toLowerCase()
  if (domain === 'localhost') return true
  return /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/u.test(domain)
}

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(value.trim())
}

function randomSecret(bytes = 24) {
  return randomBytes(bytes).toString('base64url')
}

function randomDatabaseUsername(prefix) {
  return `${prefix}_${randomBytes(6).toString('hex')}`
}

function setEnvValue(text, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'mu')
  return pattern.test(text) ? text.replace(pattern, line) : `${text.trimEnd()}\n${line}\n`
}

function getEnvValue(text, key, fallback = '') {
  const pattern = new RegExp(`^${key}=(.*)$`, 'mu')
  return text.match(pattern)?.[1] ?? fallback
}

function readBaseEnv() {
  if (existsSync(envFile)) return readFileSync(envFile, 'utf8')
  return readFileSync(exampleEnvFile, 'utf8')
}

function saveProxyOverride(proxy) {
  if (proxy === 'caddy') {
    if (existsSync(overrideFile)) unlinkSync(overrideFile)
    return
  }

  writeFileSync(
    overrideFile,
    `# Generated by OpenBcon Bootstrap Setup.\n# Traefik must route the public host to 127.0.0.1:8080.\nservices:\n  caddy:\n    ports:\n      - "127.0.0.1:8080:80"\n    volumes:\n      - ./Caddyfile.http:/etc/caddy/Caddyfile:ro\n      - caddy-data:/data\n      - caddy-config:/config\n`,
    { mode: 0o600 },
  )
}

function buildEnvironment(input) {
  const domain = input.domain.trim().toLowerCase()
  const publicUrl = domain === 'localhost' ? 'http://localhost' : `https://${domain}`
  let text = readBaseEnv()
  text = text.replaceAll('your-domain.example', domain)
  text = setEnvValue(text, 'DOMAIN', domain)
  text = setEnvValue(text, 'ACME_EMAIL', input.certificateEmail.trim())
  text = setEnvValue(text, 'PUBLIC_APP_URL', publicUrl)
  text = setEnvValue(text, 'OPENBCON_ENVIRONMENT_MODE', input.environmentMode)

  // Generate server-side secrets so the setup form never transports them.
  if (!/^POSTGRES_USER=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'POSTGRES_USER', randomDatabaseUsername('obc_pg'))
  }
  if (!/^POSTGRES_PASSWORD=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'POSTGRES_PASSWORD', randomSecret())
  }
  if (!/^MONGODB_ROOT_USERNAME=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'MONGODB_ROOT_USERNAME', randomDatabaseUsername('obc_mongo'))
  }
  if (!/^MONGODB_ROOT_PASSWORD=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'MONGODB_ROOT_PASSWORD', randomSecret())
  }
  if (!/^APP_STATE_ENCRYPTION_KEY=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'APP_STATE_ENCRYPTION_KEY', randomBytes(32).toString('hex'))
  }

  // Keep every service on the same credentials and on the required
  // shared/test/live database names. This prevents a generated password from
  // drifting away from the connection URLs in the production example.
  const postgresUser = getEnvValue(text, 'POSTGRES_USER', 'bconomics')
  const postgresPassword = getEnvValue(text, 'POSTGRES_PASSWORD')
  const postgresUrl = (database) =>
    `postgresql://${encodeURIComponent(postgresUser)}:${encodeURIComponent(postgresPassword)}@postgres:5432/${database}`
  const syncLocalPostgresUrl = (key, database) => {
    const current = getEnvValue(text, key)
    if (!current || current.includes('@postgres:5432/')) {
      text = setEnvValue(text, key, postgresUrl(database))
    }
  }
  syncLocalPostgresUrl('DATABASE_URL_SHARED', 'bconomics')
  syncLocalPostgresUrl('DATABASE_URL_TEST', 'bconomics_test')
  syncLocalPostgresUrl('DATABASE_URL_LIVE', 'bconomics_live')
  syncLocalPostgresUrl('OPENBCON_DB_DSN_SHARED', 'bconomics')
  syncLocalPostgresUrl('OPENBCON_DB_DSN_TEST', 'bconomics_test')
  syncLocalPostgresUrl('OPENBCON_DB_DSN_LIVE', 'bconomics_live')

  const sharedMongo = getEnvValue(text, 'MONGODB_DATABASE_SHARED', 'bconomics')
  const testMongo = getEnvValue(text, 'MONGODB_DATABASE_TEST', 'bconomics_test')
  const liveMongo = getEnvValue(text, 'MONGODB_DATABASE_LIVE', 'bconomics_live')
  text = setEnvValue(text, 'MONGODB_DATABASE_SHARED', sharedMongo)
  text = setEnvValue(text, 'MONGODB_DATABASE_TEST', testMongo)
  text = setEnvValue(text, 'MONGODB_DATABASE_LIVE', liveMongo)
  text = setEnvValue(text, 'OPENBCON_MONGODB_DATABASE_SHARED', sharedMongo)
  text = setEnvValue(text, 'OPENBCON_MONGODB_DATABASE_TEST', testMongo)
  text = setEnvValue(text, 'OPENBCON_MONGODB_DATABASE_LIVE', liveMongo)

  return text.endsWith('\n') ? text : `${text}\n`
}

function databaseCredentials(text) {
  return {
    postgres: {
      username: getEnvValue(text, 'POSTGRES_USER'),
      password: getEnvValue(text, 'POSTGRES_PASSWORD'),
    },
    mongodb: {
      username: getEnvValue(text, 'MONGODB_ROOT_USERNAME'),
      password: getEnvValue(text, 'MONGODB_ROOT_PASSWORD'),
    },
  }
}

function writeEnvironment(input) {
  const nextEnv = buildEnvironment(input)
  const tempFile = `${envFile}.tmp-${process.pid}`
  writeFileSync(tempFile, nextEnv, { mode: 0o600 })
  if (existsSync(envFile)) {
    renameSync(envFile, `${envFile}.backup-${Date.now()}`)
  }
  renameSync(tempFile, envFile)
  saveProxyOverride(input.proxy)
  writeFileSync(completionFile, new Date().toISOString(), { mode: 0o600 })
  writeStatus('configuration_saved', 'Configuration was written to deploy/.env.production.')
  setupInput = input
  setupCompleted = true
  return databaseCredentials(nextEnv)
}

function writeStatus(phase, message) {
  writeFileSync(statusFile, JSON.stringify({ phase, message, updatedAt: new Date().toISOString() }) + '\n', { mode: 0o600 })
}

function readStatus() {
  if (!existsSync(statusFile)) return { phase: 'waiting', message: 'Waiting for configuration.' }
  try {
    return JSON.parse(readFileSync(statusFile, 'utf8'))
  } catch {
    return { phase: 'failed', message: 'The deployment status file could not be read.' }
  }
}

function configuredDomain() {
  if (setupInput?.domain) return setupInput.domain.trim().toLowerCase()
  if (!existsSync(envFile)) return ''
  const match = readFileSync(envFile, 'utf8').match(/^DOMAIN=(.+)$/mu)
  return match?.[1]?.trim().toLowerCase() || ''
}

async function checkDns(domain) {
  if (domain === 'localhost') return { status: 'ready', message: 'Localhost is available.', addresses: ['127.0.0.1'] }
  try {
    const records = await lookup(domain, { all: true })
    const addresses = records.map((record) => record.address)
    const pointsToServer = addresses.includes(serverAddress) || addresses.length > 0 && !/^\d{1,3}(?:\.\d{1,3}){3}$/u.test(serverAddress)
    return {
      status: pointsToServer ? 'ready' : 'warning',
      message: pointsToServer ? `DNS resolves to ${addresses.join(', ')}.` : `DNS resolves, but not to ${serverAddress}.`,
      addresses,
    }
  } catch {
    return { status: 'pending', message: 'DNS is not resolving yet. Create or update the domain A record.', addresses: [] }
  }
}

async function checkApplication(domain, dnsStatus) {
  if (!domain || dnsStatus.status !== 'ready') return { status: 'pending', message: 'Waiting for DNS before checking HTTPS and the API.' }
  const protocol = domain === 'localhost' ? 'http' : 'https'
  try {
    const response = await fetch(`${protocol}://${domain}/api/health`, { signal: AbortSignal.timeout(5000) })
    if (!response.ok) return { status: 'pending', message: `The public endpoint returned HTTP ${response.status}.` }
    const payload = await response.json().catch(() => ({}))
    return { status: payload.status === 'ok' ? 'ready' : 'warning', message: payload.status === 'ok' ? 'HTTPS and the API health check are ready.' : 'The endpoint responded, but the API is not healthy yet.' }
  } catch (error) {
    const code = error?.cause?.code || error?.code || ''
    if (code === 'ECONNREFUSED') return { status: 'warning', message: 'HTTPS connection was refused. Check that TCP 443 is open and Caddy or Traefik owns the port.' }
    if (code === 'ENOTFOUND' || code === 'EAI_AGAIN') return { status: 'warning', message: 'The domain could not be resolved from the VPS. Check the DNS A/AAAA records.' }
    if (code.startsWith('ERR_SSL') || code.includes('TLS') || String(error?.message).toLowerCase().includes('certificate')) {
      return { status: 'warning', message: 'The HTTPS handshake failed. Check Caddy or Traefik certificate logs and confirm the selected proxy mode.' }
    }
    if (code === 'ETIMEDOUT' || code === 'UND_ERR_CONNECT_TIMEOUT') return { status: 'warning', message: 'HTTPS timed out. Check firewall rules for TCP 80 and 443 and verify the proxy is reachable.' }
    return { status: 'pending', message: `The public health check is waiting: ${error?.message || 'the application is still starting.'}` }
  }
}

async function statusPayload() {
  const deployment = readStatus()
  const domain = configuredDomain()
  if (!domain) return { ...deployment, dns: { status: 'pending', message: 'Save the deployment form to check the domain.' }, application: { status: 'pending', message: 'Waiting for configuration.' } }
  const dns = await checkDns(domain)
  const application = await checkApplication(domain, dns)
  return { ...deployment, configurationSaved: existsSync(completionFile), domain, publicUrl: domain === 'localhost' ? 'http://localhost' : `https://${domain}`, dns, application }
}

function page() {
  const setupToken = JSON.stringify(token)
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenBcon deployment setup</title>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #17213b; background: #f4f7fb; }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; display: grid; place-items: center; padding: 28px; }
    main { width: min(760px, 100%); padding: 34px; border: 1px solid #dfe5f0; border-radius: 22px; background: white; box-shadow: 0 24px 70px #17213b18; }
    .eyebrow { color: #5760d9; font-size: 12px; font-weight: 800; letter-spacing: .14em; text-transform: uppercase; }
    h1 { margin: 10px 0; font-size: clamp(2rem, 5vw, 3.4rem); letter-spacing: -.06em; }
    p { color: #6f7890; line-height: 1.65; }
    .steps { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin: 26px 0; }
    .step { padding: 12px; border-radius: 10px; background: #f4f6fb; color: #7c8497; font-size: 12px; font-weight: 800; }
    .step.active { background: #eef0ff; color: #3340a5; }
    form { display: grid; gap: 18px; }
    label { display: grid; gap: 7px; color: #30394e; font-size: 13px; font-weight: 800; }
    input, select { width: 100%; min-height: 46px; padding: 10px 12px; border: 1px solid #d9dfea; border-radius: 10px; background: #fff; color: #17213b; font: inherit; }
    small { color: #858c9d; font-weight: 500; line-height: 1.5; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 14px; }
    .choice { display: grid; gap: 6px; padding: 15px; border: 1px solid #dfe5f0; border-radius: 12px; cursor: pointer; }
    .choice:has(input:checked) { border-color: #5760d9; box-shadow: 0 0 0 3px #5760d91a; }
    .choice input { width: auto; min-height: auto; }
    .notice { padding: 13px 15px; border-radius: 11px; background: #fff8e9; color: #795b29; font-size: 13px; line-height: 1.55; }
    .status-panel { display: grid; gap: 18px; }
    .status-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; padding-bottom: 6px; }
    .status-head strong { display: block; font-size: 18px; }
    .status-head p { margin: 6px 0 0; }
    .status-badge, .status-state { display: inline-flex; align-items: center; white-space: nowrap; border-radius: 999px; padding: 6px 10px; background: #f0f2f7; color: #747d92; font-size: 12px; font-weight: 800; }
    .status-badge.ready, .status-state.ready { background: #e5f7ee; color: #218354; }
    .status-badge.failed, .status-state.failed { background: #fff0f0; color: #a64040; }
    .status-badge.warning, .status-state.warning { background: #fff5dd; color: #8a6727; }
    .status-list { display: grid; gap: 10px; }
    .status-row { display: grid; grid-template-columns: 12px 1fr auto; align-items: center; gap: 12px; padding: 14px; border: 1px solid #e1e6f0; border-radius: 12px; }
    .status-row strong { display: block; color: #30394e; font-size: 13px; }
    .status-row small { display: block; margin-top: 4px; }
    .status-dot { width: 10px; height: 10px; border-radius: 50%; background: #aeb6c7; }
    .status-row.ready .status-dot { background: #2bb673; }
    .status-row.warning .status-dot { background: #e0a52b; }
    .status-row.failed .status-dot { background: #d45b5b; }
    .next-step { padding: 16px; border-radius: 12px; background: #eef3ff; color: #3340a5; }
    .next-step strong { display: block; font-size: 13px; }
    .next-step p { margin: 5px 0 0; color: #59658c; font-size: 13px; }
    .credentials { display: grid; gap: 10px; padding: 16px; border: 1px solid #dfe5f0; border-radius: 12px; background: #fbfcff; }
    .credentials h2 { margin: 0; font-size: 16px; }
    .credentials p { margin: 0; font-size: 13px; }
    .credential-group { display: grid; gap: 8px; }
    .credential-group strong { color: #30394e; font-size: 13px; }
    .credential-row { display: grid; grid-template-columns: 120px 1fr auto; align-items: center; gap: 8px; }
    .credential-row span { color: #747d92; font-size: 12px; font-weight: 800; }
    .credential-row code { min-width: 0; overflow-wrap: anywhere; }
    .copy-button { min-height: 32px; padding: 0 10px; background: #eef0ff; color: #3340a5; font-size: 12px; }
    .credential-warning { padding: 12px 13px; border-radius: 10px; background: #fff4e7; color: #7d5424; font-size: 13px; line-height: 1.55; }
    .credential-warning strong { display: block; margin-bottom: 4px; }
    .credential-warning p { margin: 0; color: #7d5424; font-size: 13px; }
    .credential-warning a { color: #6c4b20; font-weight: 800; }
    .error { display: none; padding: 12px 14px; border-radius: 10px; background: #fff1f1; color: #a64040; font-size: 13px; }
    button { min-height: 46px; padding: 0 18px; border: 0; border-radius: 10px; background: #5760d9; color: white; font: inherit; font-weight: 800; cursor: pointer; }
    button:disabled { opacity: .6; cursor: wait; }
    .footer { display: flex; justify-content: flex-end; margin-top: 24px; }
    code { padding: 2px 5px; border-radius: 5px; background: #edf0f6; font-size: .9em; }
    @media (max-width: 620px) { main { padding: 24px; } .grid { grid-template-columns: 1fr; } .steps { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <main>
    <span class="eyebrow">OpenBcon Bootstrap Setup</span>
    <h1>Connect your deployment.</h1>
    <p>Set the domain and server routing before OpenBcon starts. This temporary setup page runs only once and writes the configuration on this VPS.</p>
    <div class="steps"><div class="step active">01 Domain</div><div class="step active">02 HTTPS</div><div class="step active">03 Start</div></div>
    <form id="setup-form">
      <div class="grid">
        <label>Public domain<input name="domain" placeholder="client.example.com" required spellcheck="false"><small>Point an A record for this domain to <strong>${escapeHtml(serverAddress)}</strong> first.</small></label>
        <label>Certificate email<input name="certificateEmail" type="email" placeholder="admin@client.com" required><small>Used for Let&apos;s Encrypt renewal notices.</small></label>
      </div>
      <div class="grid">
        <label class="choice"><input type="radio" name="proxy" value="caddy" checked><strong>Caddy direct</strong><small>OpenBcon owns ports 80 and 443 and issues HTTPS automatically.</small></label>
        <label class="choice"><input type="radio" name="proxy" value="traefik"><strong>Existing Traefik</strong><small>Keep Traefik on 80/443. The setup creates a local Caddy route on 127.0.0.1:8080.</small></label>
      </div>
      <label>Initial runtime mode<select name="environmentMode"><option value="test">Test Mode - recommended</option><option value="live">Live Mode</option></select><small>Test Mode is safer for first launch. You can change the server environment later.</small></label>
      <div class="notice"><strong>Security:</strong> database accounts, passwords, and the application encryption key are generated inside the VPS. This page uses a one-time token, expires after 24 hours, and shuts down after saving. Port 8090 is only needed during setup and should be closed in the VPS firewall afterward.</div>
      <div class="error" id="error" role="alert"></div>
      <div class="footer"><button id="submit" type="submit">Save and start OpenBcon</button></div>
    </form>
  </main>
  <script>
    const token = ${setupToken};
    const serverAddress = ${JSON.stringify(serverAddress)};
    const form = document.querySelector('#setup-form');
    const error = document.querySelector('#error');
    const submit = document.querySelector('#submit');
    const statusPanelMarkup = '<section class="status-panel" aria-live="polite">' +
      '<div class="status-head"><div><strong id="status-title">Deployment in progress.</strong><p id="status-message">Checking the deployment status...</p></div><span id="overall-badge" class="status-badge">Checking</span></div>' +
      '<div class="status-list">' +
        '<div class="status-row" id="config-row"><span class="status-dot"></span><div><strong>Configuration written</strong><small>Waiting for the VPS to save the environment file.</small></div><span class="status-state">Waiting</span></div>' +
        '<div class="status-row" id="dns-row"><span class="status-dot"></span><div><strong>Domain connection</strong><small>Checking DNS resolution.</small></div><span class="status-state">Checking</span></div>' +
        '<div class="status-row" id="services-row"><span class="status-dot"></span><div><strong>OpenBcon services</strong><small>Waiting for the deployment to start.</small></div><span class="status-state">Waiting</span></div>' +
        '<div class="status-row" id="health-row"><span class="status-dot"></span><div><strong>HTTPS and API health</strong><small>Waiting for the public URL.</small></div><span class="status-state">Waiting</span></div>' +
      '</div>' +
      '<div class="credentials"><h2>Database credentials</h2><p>Save these credentials in a secure password manager. They are generated on the VPS and are not shown again after this setup session.</p>' +
        '<div class="credential-group"><strong>PostgreSQL</strong>' +
          '<div class="credential-row"><span>Username</span><code data-credential="postgres.username">Generating...</code><button class="copy-button" type="button" data-copy="postgres.username">Copy</button></div>' +
          '<div class="credential-row"><span>Password</span><code data-credential="postgres.password">Generating...</code><button class="copy-button" type="button" data-copy="postgres.password">Copy</button></div>' +
        '</div>' +
        '<div class="credential-group"><strong>MongoDB</strong>' +
          '<div class="credential-row"><span>Username</span><code data-credential="mongodb.username">Generating...</code><button class="copy-button" type="button" data-copy="mongodb.username">Copy</button></div>' +
          '<div class="credential-row"><span>Password</span><code data-credential="mongodb.password">Generating...</code><button class="copy-button" type="button" data-copy="mongodb.password">Copy</button></div>' +
        '</div>' +
        '<div class="credential-warning"><strong>Change these passwords soon.</strong><p>After OpenBcon is healthy, rotate both database passwords. Update the database accounts and every matching value in <code>deploy/.env.production</code> together, then recreate the application containers. Never change the env file alone. See the <a href="https://github.com/adm73/OpenBcon/blob/main/docs/deployment/hostinger-vps.md#rotate-database-credentials" target="_blank" rel="noreferrer">password rotation instructions</a>.</p></div>' +
      '</div>' +
      '<div class="next-step" id="next-step"><strong>Next step</strong><p>Keep this page open while the VPS starts OpenBcon.</p></div>' +
    '</section>';

    function statusLabel(status) {
      return status === 'ready' ? 'Ready' : status === 'failed' ? 'Failed' : status === 'warning' ? 'Check' : 'Checking';
    }

    function updateRow(id, status, message) {
      const row = document.querySelector('#' + id);
      const state = row.querySelector('.status-state');
      row.classList.remove('ready', 'warning', 'failed');
      if (status === 'ready' || status === 'warning' || status === 'failed') row.classList.add(status);
      state.className = 'status-state ' + status;
      state.textContent = statusLabel(status);
      row.querySelector('small').textContent = message;
    }

    function renderCredentials(credentials) {
      if (!credentials) return;
      for (const [engine, values] of Object.entries(credentials)) {
        for (const [field, value] of Object.entries(values)) {
          const selector = '[data-credential="' + engine + '.' + field + '"]';
          const element = document.querySelector(selector);
          if (element) element.textContent = value;
        }
      }
      document.querySelectorAll('[data-copy]').forEach((button) => {
        button.addEventListener('click', async () => {
          const value = document.querySelector('[data-credential="' + button.dataset.copy + '"]')?.textContent || '';
          try {
            await navigator.clipboard.writeText(value);
            button.textContent = 'Copied';
            window.setTimeout(() => { button.textContent = 'Copy'; }, 1500);
          } catch {
            button.textContent = 'Copy manually';
          }
        });
      });
    }

    async function refreshStatus() {
      try {
        const response = await fetch('/api/status?token=' + encodeURIComponent(token), { cache: 'no-store' });
        if (!response.ok) throw new Error('The setup status page is no longer available.');
        const payload = await response.json();
        const failed = payload.phase === 'failed';
        const completed = payload.phase === 'completed' && payload.application.status === 'ready';
        const deploymentStatus = failed ? 'failed' : completed ? 'ready' : 'pending';
        const badge = document.querySelector('#overall-badge');
        badge.className = 'status-badge ' + deploymentStatus;
        badge.textContent = failed ? 'Failed' : completed ? 'Ready' : 'In progress';
        document.querySelector('#status-title').textContent = failed ? 'Deployment needs attention.' : completed ? 'OpenBcon is ready.' : 'Deployment in progress.';
        document.querySelector('#status-message').textContent = payload.message || 'Checking the deployment status...';
        const configStatus = payload.configurationSaved ? 'ready' : failed ? 'failed' : 'pending';
        updateRow('config-row', configStatus, payload.configurationSaved ? 'Written to deploy/.env.production on the VPS.' : failed ? 'The environment file was not written.' : 'Waiting for the VPS to save the environment file.');
        updateRow('dns-row', payload.dns.status, payload.dns.message);
        const servicesReady = ['services_ready', 'verifying', 'completed'].includes(payload.phase);
        const servicesStatus = failed ? 'failed' : servicesReady ? 'ready' : 'pending';
        updateRow('services-row', servicesStatus, failed ? payload.message : servicesReady ? 'PostgreSQL, MongoDB, Ollama, API, Python, and Caddy are healthy.' : payload.message || 'The VPS is starting the services.');
        updateRow('health-row', failed ? 'failed' : payload.application.status, payload.application.message);
        const nextStep = document.querySelector('#next-step p');
        if (failed) nextStep.textContent = 'Review the deploy.sh terminal output, fix the reported issue, then run ./deploy/deploy.sh --setup again.';
        else if (completed) nextStep.textContent = 'Open ' + payload.publicUrl + '. Then close inbound TCP port 8090 in the VPS firewall.';
        else if (payload.dns.status !== 'ready') nextStep.textContent = 'Point an A record for your domain to ' + serverAddress + '. DNS changes may take a few minutes.';
        else if (payload.application.status === 'warning') nextStep.textContent = 'Review the HTTPS message above, then inspect the Caddy or Traefik logs before retrying setup.';
        else nextStep.textContent = 'Keep this page open. The VPS is starting OpenBcon and will test HTTPS and /api/health automatically.';
        if (!failed && !completed) window.setTimeout(refreshStatus, 2500);
      } catch (requestError) {
        document.querySelector('#status-message').textContent = requestError.message || 'The status check failed. Refresh this page to try again.';
        window.setTimeout(refreshStatus, 5000);
      }
    }

    form.addEventListener('submit', async (event) => {
      event.preventDefault();
      error.style.display = 'none';
      submit.disabled = true;
      try {
        const data = Object.fromEntries(new FormData(form).entries());
        const response = await fetch('/api/setup', { method: 'POST', headers: { 'content-type': 'application/json', 'x-openbcon-setup-token': token }, body: JSON.stringify(data) });
        const payload = await response.json();
        if (!response.ok) throw new Error(payload.message || 'Setup could not be saved.');
        form.innerHTML = statusPanelMarkup;
        renderCredentials(payload.databaseCredentials);
        refreshStatus();
      } catch (requestError) {
        error.textContent = requestError.message || 'Setup could not be saved.';
        error.style.display = 'block';
        submit.disabled = false;
      }
    });
  </script>
</body>
</html>`
}

function readBody(request) {
  return new Promise((resolve, reject) => {
    let body = ''
    request.on('data', (chunk) => {
      body += chunk
      if (body.length > 32_000) reject(new Error('Request body is too large.'))
    })
    request.on('end', () => resolve(body))
    request.on('error', reject)
  })
}

function authorized(request, url) {
  return request.headers['x-openbcon-setup-token'] === token || url.searchParams.get('token') === token
}

const server = http.createServer(async (request, response) => {
  const url = new URL(request.url || '/', `http://${request.headers.host || '127.0.0.1'}`)
  if (!authorized(request, url)) {
    response.writeHead(404)
    response.end('Not found')
    return
  }

  if (request.method === 'GET' && url.pathname === '/setup') {
    response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' })
    response.end(page())
    return
  }

  if (request.method === 'GET' && url.pathname === '/api/status') {
    response.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' })
    response.end(JSON.stringify(await statusPayload()))
    return
  }

  if (request.method === 'POST' && url.pathname === '/api/setup') {
    if (setupCompleted) {
      response.writeHead(409, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ message: 'Setup has already been saved. Refresh the status page.' }))
      return
    }
    try {
      const input = JSON.parse(await readBody(request))
      if (!isValidDomain(input.domain || '')) throw new Error('Enter a valid public domain.')
      if (!isValidEmail(input.certificateEmail || '')) throw new Error('Enter a valid certificate email.')
      if (!['caddy', 'traefik'].includes(input.proxy)) throw new Error('Choose a supported proxy.')
      if (!['test', 'live'].includes(input.environmentMode)) throw new Error('Choose Test or Live Mode.')
      const credentials = writeEnvironment(input)
      response.writeHead(200, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ ok: true, databaseCredentials: credentials }))
    } catch (error) {
      response.writeHead(400, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ message: error instanceof Error ? error.message : 'Setup failed.' }))
    }
    return
  }

  response.writeHead(404)
  response.end('Not found')
})

const expiryTimer = setTimeout(() => {
  if (!setupCompleted) {
    process.stderr.write('OpenBcon setup expired without being completed.\n')
    server.close(() => process.exit(2))
  }
}, ttlSeconds * 1000)
expiryTimer.unref()

server.listen(port, bindAddress, () => {
  process.stdout.write(`OpenBcon setup server listening on http://${bindAddress}:${port}/setup?token=${token}\n`)
})
