import http from 'node:http'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { URL } from 'node:url'

const setupRoot = process.env.SETUP_ROOT || '/setup'
const token = process.env.SETUP_TOKEN || ''
const serverAddress = process.env.SERVER_ADDRESS || 'the VPS address'
const envFile = join(setupRoot, '.env.production')
const exampleEnvFile = join(setupRoot, '.env.production.example')
const overrideFile = join(setupRoot, 'docker-compose.proxy.yml')
const completionFile = join(setupRoot, '.setup-complete')
const port = Number(process.env.SETUP_PORT || 8090)

if (!token) throw new Error('SETUP_TOKEN is required.')

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function isValidDomain(value) {
  const domain = value.trim().toLowerCase()
  if (domain === 'localhost') return true
  return /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/u.test(domain)
}

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(value.trim())
}

function randomSecret(bytes = 24) {
  return randomBytes(bytes).toString('base64url')
}

function setEnvValue(text, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'mu')
  return pattern.test(text) ? text.replace(pattern, line) : `${text.trimEnd()}\n${line}\n`
}

function readBaseEnv() {
  if (existsSync(envFile)) return readFileSync(envFile, 'utf8')
  return readFileSync(exampleEnvFile, 'utf8')
}

function saveProxyOverride(proxy) {
  if (proxy === 'caddy') {
    if (existsSync(overrideFile)) unlinkSync(overrideFile)
    return
  }

  writeFileSync(
    overrideFile,
    `# Generated by OpenBcon Bootstrap Setup.\n# Traefik must route the public host to 127.0.0.1:8080.\nservices:\n  caddy:\n    ports:\n      - "127.0.0.1:8080:80"\n`,
    { mode: 0o600 },
  )
}

function buildEnvironment(input) {
  const domain = input.domain.trim().toLowerCase()
  const publicUrl = domain === 'localhost' ? 'http://localhost' : `https://${domain}`
  let text = readBaseEnv()
  text = text.replaceAll('your-domain.example', domain)
  text = setEnvValue(text, 'DOMAIN', domain)
  text = setEnvValue(text, 'ACME_EMAIL', input.certificateEmail.trim())
  text = setEnvValue(text, 'PUBLIC_APP_URL', publicUrl)
  text = setEnvValue(text, 'OPENBCON_ENVIRONMENT_MODE', input.environmentMode)

  // Generate server-side secrets so the setup form never transports them.
  if (!/^POSTGRES_PASSWORD=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'POSTGRES_PASSWORD', randomSecret())
  }
  if (!/^MONGODB_ROOT_PASSWORD=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'MONGODB_ROOT_PASSWORD', randomSecret())
  }
  if (!/^APP_STATE_ENCRYPTION_KEY=(?!replace_with_)/mu.test(text)) {
    text = setEnvValue(text, 'APP_STATE_ENCRYPTION_KEY', randomBytes(32).toString('hex'))
  }

  return text.endsWith('\n') ? text : `${text}\n`
}

function writeEnvironment(input) {
  const nextEnv = buildEnvironment(input)
  const tempFile = `${envFile}.tmp-${process.pid}`
  writeFileSync(tempFile, nextEnv, { mode: 0o600 })
  if (existsSync(envFile)) {
    renameSync(envFile, `${envFile}.backup-${Date.now()}`)
  }
  renameSync(tempFile, envFile)
  saveProxyOverride(input.proxy)
  writeFileSync(completionFile, new Date().toISOString(), { mode: 0o600 })
}

function page() {
  const setupToken = JSON.stringify(token)
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenBcon deployment setup</title>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #17213b; background: #f4f7fb; }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; display: grid; place-items: center; padding: 28px; }
    main { width: min(760px, 100%); padding: 34px; border: 1px solid #dfe5f0; border-radius: 22px; background: white; box-shadow: 0 24px 70px #17213b18; }
    .eyebrow { color: #5760d9; font-size: 12px; font-weight: 800; letter-spacing: .14em; text-transform: uppercase; }
    h1 { margin: 10px 0; font-size: clamp(2rem, 5vw, 3.4rem); letter-spacing: -.06em; }
    p { color: #6f7890; line-height: 1.65; }
    .steps { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin: 26px 0; }
    .step { padding: 12px; border-radius: 10px; background: #f4f6fb; color: #7c8497; font-size: 12px; font-weight: 800; }
    .step.active { background: #eef0ff; color: #3340a5; }
    form { display: grid; gap: 18px; }
    label { display: grid; gap: 7px; color: #30394e; font-size: 13px; font-weight: 800; }
    input, select { width: 100%; min-height: 46px; padding: 10px 12px; border: 1px solid #d9dfea; border-radius: 10px; background: #fff; color: #17213b; font: inherit; }
    small { color: #858c9d; font-weight: 500; line-height: 1.5; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 14px; }
    .choice { display: grid; gap: 6px; padding: 15px; border: 1px solid #dfe5f0; border-radius: 12px; cursor: pointer; }
    .choice:has(input:checked) { border-color: #5760d9; box-shadow: 0 0 0 3px #5760d91a; }
    .choice input { width: auto; min-height: auto; }
    .notice { padding: 13px 15px; border-radius: 11px; background: #fff8e9; color: #795b29; font-size: 13px; line-height: 1.55; }
    .error { display: none; padding: 12px 14px; border-radius: 10px; background: #fff1f1; color: #a64040; font-size: 13px; }
    button { min-height: 46px; padding: 0 18px; border: 0; border-radius: 10px; background: #5760d9; color: white; font: inherit; font-weight: 800; cursor: pointer; }
    button:disabled { opacity: .6; cursor: wait; }
    .footer { display: flex; justify-content: flex-end; margin-top: 24px; }
    code { padding: 2px 5px; border-radius: 5px; background: #edf0f6; font-size: .9em; }
    @media (max-width: 620px) { main { padding: 24px; } .grid { grid-template-columns: 1fr; } .steps { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <main>
    <span class="eyebrow">OpenBcon Bootstrap Setup</span>
    <h1>Connect your deployment.</h1>
    <p>Set the domain and server routing before OpenBcon starts. This setup runs only once and writes the configuration on this VPS.</p>
    <div class="steps"><div class="step active">01 Domain</div><div class="step active">02 HTTPS</div><div class="step active">03 Start</div></div>
    <form id="setup-form">
      <div class="grid">
        <label>Public domain<input name="domain" placeholder="client.example.com" required spellcheck="false"><small>Point an A record for this domain to <strong>${escapeHtml(serverAddress)}</strong> first.</small></label>
        <label>Certificate email<input name="certificateEmail" type="email" placeholder="admin@client.com" required><small>Used for Let&apos;s Encrypt renewal notices.</small></label>
      </div>
      <div class="grid">
        <label class="choice"><input type="radio" name="proxy" value="caddy" checked><strong>Caddy direct</strong><small>OpenBcon owns ports 80 and 443 and issues HTTPS automatically.</small></label>
        <label class="choice"><input type="radio" name="proxy" value="traefik"><strong>Existing Traefik</strong><small>Keep Traefik on 80/443. The setup creates a local Caddy route on 127.0.0.1:8080.</small></label>
      </div>
      <label>Initial runtime mode<select name="environmentMode"><option value="test">Test Mode - recommended</option><option value="live">Live Mode</option></select><small>Test Mode is safer for first launch. You can change the server environment later.</small></label>
      <div class="notice"><strong>Security:</strong> database passwords and the application encryption key are generated inside the VPS. This page does not ask for or transmit API keys. Use an SSH tunnel to open it; do not expose port 8090 publicly.</div>
      <div class="error" id="error" role="alert"></div>
      <div class="footer"><button id="submit" type="submit">Save and start OpenBcon</button></div>
    </form>
  </main>
  <script>
    const token = ${setupToken};
    const form = document.querySelector('#setup-form');
    const error = document.querySelector('#error');
    const submit = document.querySelector('#submit');
    form.addEventListener('submit', async (event) => {
      event.preventDefault();
      error.style.display = 'none';
      submit.disabled = true;
      try {
        const data = Object.fromEntries(new FormData(form).entries());
        const response = await fetch('/api/setup', { method: 'POST', headers: { 'content-type': 'application/json', 'x-openbcon-setup-token': token }, body: JSON.stringify(data) });
        const payload = await response.json();
        if (!response.ok) throw new Error(payload.message || 'Setup could not be saved.');
        form.innerHTML = '<div class="notice"><strong>Configuration saved.</strong><p>You can close this page. The deploy script is now starting PostgreSQL, MongoDB, Ollama, the API, and the HTTPS proxy.</p></div>';
      } catch (requestError) {
        error.textContent = requestError.message || 'Setup could not be saved.';
        error.style.display = 'block';
        submit.disabled = false;
      }
    });
  </script>
</body>
</html>`
}

function readBody(request) {
  return new Promise((resolve, reject) => {
    let body = ''
    request.on('data', (chunk) => {
      body += chunk
      if (body.length > 32_000) reject(new Error('Request body is too large.'))
    })
    request.on('end', () => resolve(body))
    request.on('error', reject)
  })
}

function authorized(request, url) {
  return request.headers['x-openbcon-setup-token'] === token || url.searchParams.get('token') === token
}

const server = http.createServer(async (request, response) => {
  const url = new URL(request.url || '/', `http://${request.headers.host || '127.0.0.1'}`)
  if (!authorized(request, url)) {
    response.writeHead(404)
    response.end('Not found')
    return
  }

  if (request.method === 'GET' && url.pathname === '/setup') {
    response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' })
    response.end(page())
    return
  }

  if (request.method === 'POST' && url.pathname === '/api/setup') {
    try {
      const input = JSON.parse(await readBody(request))
      if (!isValidDomain(input.domain || '')) throw new Error('Enter a valid public domain.')
      if (!isValidEmail(input.certificateEmail || '')) throw new Error('Enter a valid certificate email.')
      if (!['caddy', 'traefik'].includes(input.proxy)) throw new Error('Choose a supported proxy.')
      if (!['test', 'live'].includes(input.environmentMode)) throw new Error('Choose Test or Live Mode.')
      writeEnvironment(input)
      response.writeHead(200, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ ok: true }))
    } catch (error) {
      response.writeHead(400, { 'content-type': 'application/json' })
      response.end(JSON.stringify({ message: error instanceof Error ? error.message : 'Setup failed.' }))
    }
    return
  }

  response.writeHead(404)
  response.end('Not found')
})

server.listen(port, '127.0.0.1', () => {
  process.stdout.write(`OpenBcon setup server listening on http://127.0.0.1:${port}/setup?token=${token}\n`)
})
